<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.clojars.jj</groupId>
  <artifactId>bettong</artifactId>
  <packaging>jar</packaging>
  <version>0.1.0</version>
  <name>bettong</name>
  <description>A small agent library: give an agent capabilities you define, and it uses them.</description>
  <url>https://github.com/ruroru/bettong</url>
  <licenses>
    <license>
      <name>Eclipse Public License 2.0</name>
      <url>https://www.eclipse.org/legal/epl-2.0/</url>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/ruroru/bettong</url>
    <connection>scm:git:git://github.com/ruroru/bettong.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/ruroru/bettong.git</developerConnection>
    <tag>dd6f987368b419152e992aa751c26d7bcbaaa165</tag>
  </scm>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
    <resources>
      <resource>
        <directory>resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>resources</directory>
      </testResource>
    </testResources>
    <directory>target</directory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins/>
  </build>
  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>clojars</id>
      <url>https://repo.clojars.org/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
  </repositories>
  <dependencyManagement>
    <dependencies/>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.12.1</version>
    </dependency>
    <dependency>
      <groupId>org.clojars.jj</groupId>
      <artifactId>potoroo</artifactId>
      <version>0.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>data.json</artifactId>
      <version>2.5.2</version>
    </dependency>
    <dependency>
      <groupId>org.clojars.jj</groupId>
      <artifactId>ring-http-exchange</artifactId>
      <version>1.4.9</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>

<!-- This file was autogenerated by Leiningen.
  Please do not edit it directly; instead edit project.clj and regenerate it.
  It should not be considered canonical data. For more information see
  https://codeberg.org/leiningen/leiningen -->
